language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
    - 5.6
    - 7.0
    - hhvm

services:

before_install:

install:
    - travis_retry composer install

script:
    - ./vendor/bin/phpunit -c ./phpunit.xml.dist -v

after_script:
    - bash <(curl -s https://codecov.io/bash) -s .build/logs

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: 7.0
