language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
    - 7.4

services:

before_install:

install:
    - travis_retry composer install

script:
    - ./vendor/bin/phpunit -c ./phpunit.xml.dist -v

after_script:
    - bash <(curl -s https://codecov.io/bash) -s .build/logs
